import { useState, useEffect } from "react";
import axios from "axios";
import { FileText, Download, RefreshCw, AlertTriangle, Moon, Activity, Heart, Calendar } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { ScrollArea } from "@/components/ui/scroll-area";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;

export default function ReportPage() {
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(false);

  const generateReport = async () => {
    setLoading(true);
    try {
      const res = await axios.get(`${API}/report`);
      setReport(res.data.report);
    } catch (e) {
      console.error("Failed to generate report", e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    generateReport();
  }, []);

  const downloadReport = () => {
    if (!report) return;

    let text = `MomCareAI - Doctor Report\n`;
    text += `Generated: ${new Date(report.generated_at).toLocaleDateString()}\n`;
    text += `Period: ${report.period}\n`;
    text += `${"=".repeat(50)}\n\n`;
    text += `SUMMARY\n${report.summary}\n\n`;

    if (report.alerts?.length > 0) {
      text += `ALERTS\n`;
      report.alerts.forEach((a) => (text += `- ${a}\n`));
      text += "\n";
    }

    if (report.symptoms_timeline?.length > 0) {
      text += `SYMPTOMS TIMELINE\n`;
      report.symptoms_timeline.forEach((t) => {
        text += `${t.date}: ${t.symptoms.join(", ")}\n`;
      });
      text += "\n";
    }

    if (report.symptom_frequency) {
      text += `SYMPTOM FREQUENCY\n`;
      Object.entries(report.symptom_frequency)
        .sort(([, a], [, b]) => b - a)
        .forEach(([s, c]) => (text += `${s}: ${c} times\n`));
      text += "\n";
    }

    if (report.sleep_summary) {
      text += `SLEEP SUMMARY\n`;
      text += `Average: ${report.sleep_summary.average_hours}h\n`;
      text += `Low sleep days: ${report.sleep_summary.low_sleep_days}\n\n`;
    }

    if (report.recommendations?.length > 0) {
      text += `RECOMMENDATIONS\n`;
      report.recommendations.forEach((r) => (text += `- ${r}\n`));
    }

    text += `\n${"=".repeat(50)}\n`;
    text += `This report was generated by MomCareAI.\nNot a substitute for professional medical advice.\n`;

    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `momcareai-report-${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="p-6 md:p-8 max-w-3xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl sm:text-3xl font-medium text-[#2C2A29] tracking-tight" style={{ fontFamily: 'Outfit, sans-serif' }} data-testid="report-header">
            Doctor Report
          </h2>
          <p className="text-sm text-[#8A8887] mt-1">A summary you can share with your healthcare provider</p>
        </div>
        <div className="flex gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={generateReport}
            disabled={loading}
            className="rounded-full border-[#F4AAB9]/25 hover:bg-[#F4AAB9]/8 text-[#5C5A59]"
            data-testid="report-refresh"
          >
            <RefreshCw className={`w-4 h-4 mr-2 ${loading ? "animate-spin" : ""}`} />
            Refresh
          </Button>
          <Button
            size="sm"
            onClick={downloadReport}
            disabled={!report}
            className="rounded-full bg-[#F4AAB9] hover:bg-[#f09aad] text-white"
            data-testid="report-download"
          >
            <Download className="w-4 h-4 mr-2" />
            Download
          </Button>
        </div>
      </div>

      {loading && (
        <div className="text-center py-16 animate-pulse-soft">
          <RefreshCw className="w-8 h-8 mx-auto text-[#F4AAB9] animate-spin mb-3" />
          <p className="text-sm text-[#8A8887]">Generating your report...</p>
        </div>
      )}

      {!loading && report && (
        <div className="space-y-6 animate-fade-in">
          {/* Report meta */}
          <Card className="border-[#F4AAB9]/15 shadow-sm rounded-2xl" data-testid="report-summary-card">
            <CardContent className="p-6">
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 rounded-2xl bg-[#F4AAB9]/15 flex items-center justify-center">
                  <FileText className="w-5 h-5 text-[#F4AAB9]" strokeWidth={1.5} />
                </div>
                <div>
                  <p className="text-sm font-medium text-[#2C2A29]">{report.period}</p>
                  <p className="text-xs text-[#8A8887]">
                    Generated on {new Date(report.generated_at).toLocaleDateString("en-US", {
                      year: "numeric", month: "long", day: "numeric",
                    })}
                  </p>
                </div>
              </div>
              <p className="text-sm text-[#5C5A59] leading-relaxed">{report.summary}</p>
            </CardContent>
          </Card>

          {/* Alerts */}
          {report.alerts?.length > 0 && (
            <Card className="border-[#E07A5F]/20 shadow-sm rounded-2xl bg-[#E07A5F]/5" data-testid="report-alerts">
              <CardHeader className="pb-2">
                <CardTitle className="text-base font-medium text-[#E07A5F] flex items-center gap-2">
                  <AlertTriangle className="w-4 h-4" /> Alerts
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-2">
                {report.alerts.map((alert, i) => (
                  <p key={i} className="text-sm text-[#E07A5F]/80">{alert}</p>
                ))}
              </CardContent>
            </Card>
          )}

          {/* Symptoms Timeline */}
          {report.symptoms_timeline?.length > 0 && (
            <Card className="border-[#F4AAB9]/15 shadow-sm rounded-2xl" data-testid="report-symptoms-timeline">
              <CardHeader className="pb-3">
                <CardTitle className="text-lg font-medium text-[#2C2A29] flex items-center gap-2" style={{ fontFamily: 'Outfit, sans-serif' }}>
                  <Calendar className="w-4 h-4 text-[#F4AAB9]" /> Symptoms Timeline
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  {report.symptoms_timeline.map((entry, i) => (
                    <div key={i} className="flex items-start gap-3">
                      <span className="text-xs text-[#8A8887] w-20 pt-0.5 flex-shrink-0">{entry.date}</span>
                      <div className="flex flex-wrap gap-1.5">
                        {entry.symptoms.map((s) => (
                          <Badge key={s} variant="outline" className="text-xs border-[#F4AAB9]/25 text-[#5C5A59] bg-[#F4AAB9]/5 rounded-full">
                            {s}
                          </Badge>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}

          {/* Sleep Summary */}
          {report.sleep_summary && (
            <Card className="border-[#F4AAB9]/15 shadow-sm rounded-2xl" data-testid="report-sleep-summary">
              <CardHeader className="pb-3">
                <CardTitle className="text-lg font-medium text-[#2C2A29] flex items-center gap-2" style={{ fontFamily: 'Outfit, sans-serif' }}>
                  <Moon className="w-4 h-4 text-[#A8C3A6]" /> Sleep Summary
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-3 gap-4">
                  <div className="text-center p-3 rounded-xl bg-[#A8C3A6]/10">
                    <p className="text-xl font-semibold text-[#2C2A29]">{report.sleep_summary.average_hours}h</p>
                    <p className="text-xs text-[#8A8887]">Average</p>
                  </div>
                  <div className="text-center p-3 rounded-xl bg-[#F9F6F0]">
                    <p className="text-xl font-semibold text-[#2C2A29]">{report.sleep_summary.total_records}</p>
                    <p className="text-xs text-[#8A8887]">Records</p>
                  </div>
                  <div className="text-center p-3 rounded-xl bg-[#E07A5F]/8">
                    <p className="text-xl font-semibold text-[#E07A5F]">{report.sleep_summary.low_sleep_days}</p>
                    <p className="text-xs text-[#8A8887]">Low Sleep Days</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          )}

          {/* Recommendations */}
          {report.recommendations?.length > 0 && (
            <Card className="border-[#A8C3A6]/20 shadow-sm rounded-2xl bg-[#A8C3A6]/5" data-testid="report-recommendations">
              <CardHeader className="pb-2">
                <CardTitle className="text-base font-medium text-[#2C2A29] flex items-center gap-2">
                  <Heart className="w-4 h-4 text-[#A8C3A6]" /> Recommendations
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-2">
                {report.recommendations.map((rec, i) => (
                  <p key={i} className="text-sm text-[#5C5A59] leading-relaxed">{rec}</p>
                ))}
              </CardContent>
            </Card>
          )}

          {/* Disclaimer */}
          <div className="text-center py-4">
            <p className="text-xs text-[#8A8887]">
              This report is generated by MomCareAI and is not a substitute for professional medical advice.
            </p>
          </div>
        </div>
      )}

      {!loading && !report && (
        <div className="text-center py-16" data-testid="report-empty">
          <FileText className="w-12 h-12 mx-auto text-[#F4AAB9]/40 mb-4" />
          <p className="text-sm text-[#8A8887]">No report data available yet. Start chatting to build your health record.</p>
        </div>
      )}
    </div>
  );
}
